### ISSUE TITLE
训练时在跑到Epoch 12/200就停止了

### ISSUE THREAD

**Issue by coldliang** [zhouchunpong/GCN_Keras#1]
![image](https://user-images.githubusercontent.com/15016558/63672449-8e12ab00-c814-11e9-90bc-fdfc381c5f3d.png)

**Comment by zhouchunpong** [comment]
您好，我再代码中设置了early stopping（在代码中是PATIENCE参数，默认是10），当acc在连续的几个epoch中没有增加，则会自动停止。您可以把PATIENCE和NB_EPOCH设置的大一点，就不会过早的停止了。
